version: '3.1'

services:
  frontend:
    build:
      context: ./frontend
  app:
    build:
      context: .
    ports:
      - "80:8000"
    depends_on:
      - db
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: vraagdepolitiek
      MYSQL_USER: vraagdepolitiek
      MYSQL_PASSWORD: vraagdepolitiek
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
    - "8080:80"
volumes:
  mysql-data:
