# Generated by Django 2.1.1 on 2018-09-23 09:59
# Customized to populate the sites for the Sites framework

from django.db import migrations


def create_sites(apps, schema_editor):
    Site = apps.get_model('sites', 'Site')
    Site.objects.create(pk=1, domain='vraagdepolitiek.nl', name='Vraag de Politiek')
    Site.objects.create(pk=2, domain='vraagdegemeente.nl', name='Vraag de Gemeente')


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('backend', '0003_auto_20180922_1534'),
    ]

    operations = [
        migrations.RunPython(create_sites),
    ]
