# Generated by Django 2.1.1 on 2018-09-24 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20180923_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='efforts',
            field=models.TextField(blank=True, help_text='The effort that Representative has done already.'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='pledges',
            field=models.TextField(blank=True, help_text='What the Representative promises to do.'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='user',
            field=models.ForeignKey(help_text='The Representative that posted the answer.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.Representative'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='site',
            field=models.ForeignKey(default=2, help_text='The website domain the organization is displayed on.', on_delete=django.db.models.deletion.PROTECT, to='sites.Site'),
        ),
        migrations.AlterField(
            model_name='question',
            name='fb_support_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='organization',
            field=models.ForeignKey(help_text='The legislative body or municipality in which this question is posted.', on_delete=django.db.models.deletion.PROTECT, to='backend.Organization'),
        ),
        migrations.AlterField(
            model_name='question',
            name='requests',
            field=models.TextField(blank=True, help_text='What the user asks from the Representatives.'),
        ),
        migrations.AlterField(
            model_name='question',
            name='twitter_support_count',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='question',
            name='user',
            field=models.ForeignKey(help_text='The user that posted the question.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='question',
            name='user_support',
            field=models.ManyToManyField(blank=True, help_text='The users that upvoted this question.', related_name='user_support_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='representative',
            name='organization',
            field=models.ManyToManyField(blank=True, help_text='The legislative body or municipality the Representative belongs to.', to='backend.Organization'),
        ),
        migrations.AlterField(
            model_name='representative',
            name='twitter',
            field=models.CharField(blank=True, help_text='Twitter handle without the @ in the beginning.', max_length=16),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='Will be used for authentication.', max_length=254, unique=True),
        ),
    ]
