# Generated by Django 2.1.1 on 2018-09-18 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='representative',
            name='last_name',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
